### ISSUE TITLE
Warning: A non-numeric value encountered

### ISSUE THREAD

**Issue by melhirech** [mpdf/mpdf#1151]
### I found this bug / would like to have this new functionality
I have this error `Warning: A non-numeric value encountered`
when I add this CSS property `page-break-inside: avoid;`

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
"mpdf/mpdf": "^7.1"
"php": "^7.1.3"
Linux Mint 19.3
Chrome & Firefox latest version

### This is a PHP code snippet I use
```
        $html = $this->getHTMLByExfIdReffile($exfIdReffile);
        $mpdf = new Mpdf(['tempDir' => sys_get_temp_dir() . '/app', 'margin_left' => 15, 'margin_right' => 15,
            'margin_top' => 15, 'margin_bottom' => 15, 'margin_header' => 9, 'margin_footer' => 9, 'mode' => 'utf-8',
            'format' => 'A4']);
        $mpdf->charset_in = 'utf-8';
        $mpdf->WriteHTML($html);

        return $mpdf;
```
<?php

```

### This is a HTML/CSS code snippet I use

```
.itemContainer {
				margin-bottom: 10px;
				border: 1px solid #A0A9C0;
				padding: 10px;
				margin-top: 20px;
				page-break-inside: avoid;
			}
```

**Comment by finwe** [comment]
Not really helpful without your *actual* HTML code.

**Comment by finwe** [comment]
And next time you'll probably want to include the entire error message, with source file and line.

Anyway, thanks for the report and looking forward to the clarification.

**Comment by Laci357** [comment]
Hi guys! I experience the same error message, though I do not use the `page-break-inside: avoid;` css property.
´The error message says:
======
**Warning**: A non-numeric value encountered in **/var/www/testEnvironment/tools/vendor/mpdf/mpdf/src/Mpdf.php** on line **4285**

**Warning**: A non-numeric value encountered in **/var/www/testEnvironment/tools/vendor/mpdf/mpdf/src/Mpdf.php** on line **11015**
Error detected. PDF file generation aborted: A non-numeric value encountered
=====

The attached .zip file includes my folder structure, the html input file and .php file utilizing the mpdf library.I did not pack the entire "vendor" directory, since that would result in a 44MB zip file. 
**My environment**:
Debian 11
PHP version: 8.0.12

[testEnvironment.zip](https://github.com/mpdf/mpdf/files/7522804/testEnvironment.zip)

If you need any further information, let me know. 
Thank you for your help in advance.

**Comment by finwe** [comment]
@Laci357 Please create a separate issue as the reason for your error migh be different. I am closing this one as stale and missing debugging details.
