### ISSUE TITLE
mpdf/mpdf is very slow in download composer

### ISSUE THREAD

**Issue by vahidalvandi** [mpdf/mpdf#1246]
hi , why install mpdf/mpdf in composer is very slow ??? alway

**Comment by michaljusiega** [comment]
I don't understand what the problem is. The project is huge, contains a lot of files, especially the main class `mpdf/Mpdf.php` which has almost 1MB and about 30,000 lines.

Maybe try new version '2.0.0-alpha1' of Composer which provide new improvments:
https://packagist.org/packages/composer/composer#2.0.0-alpha1

**Comment by finwe** [comment]
With the size of the library, it just takes time to fetch required files. Composer cache should help a lot 
With changes in progress, especially with custom fonts as packages, the size of the library should become much smaller.

Anyway, closing this as this is not a bug of mPDF per se.

**Comment by vahidalvandi** [comment]
maybe dependency have .git folder and download mpdf/mpdf with composer is slow

**Comment by vahidalvandi** [comment]
why download https://github.com/mpdf/mpdf/releases/tag/v8.0.7 is larger than 30 MB ??? 
in all tag have folder with unnecessary files . this files must be remove in product version
