### ISSUE TITLE
detect barcode type from given string

### ISSUE THREAD

**Issue by arcanisgk** [mpdf/mpdf#1326]
There is some class / library / script to complement the mpdf function.

https://mpdf.github.io/reference/html-control-tags/barcode.html

this documentation say that mpdf can generate barcodes image but need given the string code and type.

i have the barcode in my database but i dont know how to generate the string type.

Find this validator but it doesn't give more information, or how to implement:

https://stackoverflow.com/questions/29076255/how-do-i-validate-a-barcode-number-using-php
http://safe.phpclasses.net/browse/view/html/file/52225/name/test_ean.html

**Comment by finwe** [comment]
If this is a feature request, feel free to formulate it as such. Be extensive, feel free to propose concrete approach to the problem.

Otherwise please note that the Issue tracker serves mainly as a place to report bugs and request new features as noted in [Contributing guidelines](https://raw.githubusercontent.com/mpdf/mpdf/development/.github/CONTRIBUTING.md). Please do not abuse it as a general questions or troubleshooting location.

Use the the [mpdf tag](https://stackoverflow.com/questions/tagged/mpdf) at [Stack Overflow](https://stackoverflow.com/).

**Comment by finwe** [comment]
(I am afraid this will be not entirely possible given overlapping barcode formats for all the types mPDF supports. This will be better implemented on user side knowing specifics of the input data.)

**Comment by arcanisgk** [comment]
@finwe continue in https://github.com/mpdf/mpdf/issues/1327 plz not close.
