### ISSUE TITLE
In some server installs trying to attach a pdf to an email causes this PHP warning and ends up not being able to be attached to an email.

### ISSUE THREAD

**Issue by riverBanjo** [mpdf/mpdf#1335]
I'll try my best to explain what I think is happening.

[Thu Nov 26 14:50:21.206857 2020] [php7:warn] [pid 14842] [client 172.19.0.16:37140] PHP Warning: fopen(/var/www/isema.fr/www/wp-content/uploads/%O!!]#oV~`bPf!Y)QpxYJzBLzGwmrsgO)A`h--&lt;h,%y5oc1_r /b&gt;]BZd)b8]vLu/5a25b4b166e5a838d1a6e61ca2c5aca0352cf46f1468696571c3d821721623fc.pdf): failed to open stream: No such file or directory in /var/www/isema.fr/www/wp-content/plugins/cf-pdf-submissions/vendor/mpdf/mpdf/src/Mpdf.php on line 9471, referer: https://www.isema.fr/espace-candidat/inscription/

In the above warning you'll notice that the URL doesn't look wrong but it is. their is a space after the %y5oc1_r and before the /b&gt;]. That, of course, would mean that there would be no stream to open even if the temporary directory was created. If you go to the line in your code that is causing the warning you'll see that there is a space in the value for the variable $standard. When I removed that space, the pdf can attach to the email and there are no errors. 

https://github.com/mpdf/mpdf/blob/c74f13d2f50c9bdfb5f28464a1f51340e895208f/src/Mpdf.php#L9472

**Comment by riverBanjo** [comment]
@finwe I just wondered what caused you to close the issue. Is this a duplicate issue?

**Comment by Klap-in** [comment]
In the template for the issue report, you were asked to provide examples of php and html code. Is this request unclear? I’m wondering, should we ask different questions there to convince you that it is very practical to provide an small example that let us directly reproduce your issue?
Further your minimal example is used to create an unit test, so that in the future this issue will not occurs again.
