### ISSUE TITLE
Replacing a single class (MetadataWriter) in mPDF: custom PDF metadata

### ISSUE THREAD

**Issue by wq9578** [mpdf/mpdf#1880]
### Please describe the new functionality as best as you can.

For writing my own custom PDF metadata (both regular metadata and XMP metadata) I would like to replace the class [`Mpdf\Writer\MetadataWriter`](https://github.com/mpdf/mpdf/blob/development/src/Writer/MetadataWriter.php), implementing my own functions `writeInfo()` [for regular metadata] and `writeMetadata()` [for XMP metadata] without modifying the file in the `vendor` directory.

So it would be desirable to implement an option to supply the class when constructing the Mpdf object.

**Update:**

I was successful with modifying a local copy of Mpdf (altogether some 600-700 files).

However, a much better approach would be using class inheritance and overloading only the functions to be changed.
**For this, the private variables (in classes `Mpdf`, `ServiceFactory` and `MetadataWriter`) should be `protected`, not `private` in order to be accessible by the derived classes.**
Also, the deprecated `var` declarations should be replaced by `public` for improved readability:

> **Note**: The `var` keyword is only used for compatibility reasons. Since PHP 5, the keywords `private`, `protected` and `public` should be used instead.

https://www.w3schools.com/PHP/keyword_var.asp

**Comment by finwe** [comment]
The writer is not meant to be replaced, current state is desirable. If you need to modify the writer ad hoc, just create a fork and use the fork in composer (see [repositories](https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository)). 

If you have a valid use case others could benefit from, maybe the writer could be changed to allow said use case.

var in mpdf code is [currently](https://github.com/mpdf/mpdf/pull/542#issuecomment-345658243) [intentional](https://github.com/mpdf/mpdf/issues/502).
