### ISSUE TITLE
500 Errors only on scanned PDF's

### ISSUE THREAD

**Issue by nothgiel** [mpdf/mpdf#224]
I love mPDF, it's working very well in many cases for my web development.
However, when I try to import from PDF files scanned from a printer, the PDF's will not process and I get a 500 error. On all other PDF's saved on a computer it processes and imports perfectly.

I even went so far as to purchase the commercial license of fpdi parser thinking that would fix it and it didn't.

I have attached one of these PDF's for testing. Please help! Thanks so much!

[EVSE_Agreement_mod.pdf](https://github.com/mpdf/mpdf/files/450260/EVSE_Agreement_mod.pdf)

mPDF version: 6.1.2
php version: 5.6.25

**Comment by raphjutras** [comment]
Did you find how to fix this? I am also trying to open scanned document but it doesn't work.. I'm just trying to add some text over a document for reference when we print it but it seems impossible to open such document.. Let me know if you found a fix!

**Comment by JanSlabon** [comment]
I have no problem running this file with the [FPDI PDF-Parser add-on](https://www.setasign.com/products/fpdi-pdf-parser/details/)? It uses a compression technic introduced in PDF 1.5 and can be handled with the add-on. Just pass it to the online demo.

**Comment by karishmabhosale** [comment]
Hey, 
I also faced the same problem you have been facing right now. The 500 error show due to PDF file restriction & you needs to remove that restriction from it. I remove that PDF restriction manually by following the instructions to [remove PDF restrictions](http://articles.org/learned-how-to-remove-password-from-pdf-file/).  I hope that you can take a print out after removing the restrictions.

**Comment by finwe** [comment]
Closing as stale.

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example and PHP error log excerpt to easier reproduce the error.
