### ISSUE TITLE
OverWrite not replacing text

### ISSUE THREAD

**Issue by mhoogstraten** [mpdf/mpdf#268]
### I have this problem/would like to have this functionality
I want to replace text inside a PDF document (the basics), it now shows the original PDF without replacements.

### These are mPDF and PHP versions I am using
PHP 7.0.2 and mPDF 6.1.0

### This is a PHP code snippet I use

```
<?php
//Replace these to your file locations
$inputFileName = \Yii::getAlias('@app/tmp/pdf/tmp/imation.pdf');
$outputFileName = \Yii::getAlias('@app/tmp/pdf/tmp/imation2.pdf');

//Replace contents
$mPDF = new \mPDF();
$mPDF->SetImportUse();
$mPDF->percentSubset = 0;
$mPDF->OverWrite( $inputFileName, 'naam', 'Martijn', 'F', $outputFileName ) ;

```

[imation.pdf](https://github.com/mpdf/mpdf/files/600432/imation.pdf)

**Comment by jiyanibharat303** [comment]
Please help I have checked MPDF 5.7, MPDF 6.0 and this for MPDF 7.0 and the overwrite is not working in any of them -
require_once __DIR__ . '/vendor/autoload.php';
$mpdf = new \Mpdf\Mpdf();
$mpdf->SetImportUse();
// forces no subsetting - otherwise the inserted characters may not be contained in a subset font
$mpdf->percentSubset = 0;
$mpdf->OverWrite('mpdf.pdf', 'Name', 'BHARAT', 'I', 'mpdf.pdf' ) ;

**Comment by finwe** [comment]
Closing as duplicate of (better researched) #626 - uploaded example PDF has CR line endings which OverWrite has trouble recognizing as well

**Comment by finwe** [comment]
Duplicate of #626
