### ISSUE TITLE
Where to find debug log?

### ISSUE THREAD

**Issue by baselbers** [mpdf/mpdf#331]
Is there some kind of debug log file for below debugging?
https://mpdf.github.io/reference/mpdf-variables/debug.html

**Comment by finwe** [comment]
Until mPDF `6.1.3`, the debug causes direct output of error messages. Mostly by failing via echo an exit call (`<6.1`) or an exception (`6.1.*`). There is no separate log file, only standard logging of your PHP installation and configuration.

Since 7.0-dev, you can provide your own instance of `\Psr\Log\LoggerInterface` which can then log anyway you set it up to.
