### ISSUE TITLE
Inline position absolute error

### ISSUE THREAD

**Issue by jbrooksuk** [mpdf/mpdf#344]
I'm having an issue with the following blog of HTML:

```html
<p style="right:16mm; bottom:4mm; font-size:7pt; line-height:14pt; position: absolute; text-align:right">Some text here</p>
```

It's throwing the following error:

```
ErrorException in mpdf.php line 30648:
A non-numeric value encountered
```

I'm using **v6.1.3** as I'm running PHP 7.1

FWIW, this same HTML worked in https://github.com/BlueBayTravel/mpdf/tree/new-fonts which is based on v5.3

**Comment by finwe** [comment]
Version 6.x is not compatible with 7.1. For compatibility use 7.0-dev (which is still in development and has some functionality regressions).

See also 

- https://github.com/mpdf/mpdf/issues/302
- https://github.com/mpdf/mpdf/issues/300
- https://github.com/mpdf/mpdf/issues/278

Functionality of 5.3 is probably caused by lack of 6.x features.

**Comment by jbrooksuk** [comment]
I ended up using v6.1.3 because the `development` branch is broken too:

```
ErrorException in Tag.php line 2005:
Undefined index: current
```

**Comment by finwe** [comment]
Curious. Created https://github.com/mpdf/mpdf/issues/345, thanks for reporting.
