### ISSUE TITLE
A non-numeric value encountered

### ISSUE THREAD

**Issue by prakashmalviya** [mpdf/mpdf#400]
I have used mpdf library with laravel and when i used postion absolute i have below error:

ErrorException in mpdf.php line 
17074: A non-numeric value encountered

### These are mPDF and PHP versions I am using
latest version i have

### This is a PHP code snippet I use
.myfixed2 { position: fixed;
    	overflow: auto;
    	right: 0;
    	bottom: 0mm;
    	width: 65mm;
    	border: 1px solid #880000;
    	background-color: #FFEEDD;
    	background-gradient: linear #dec7cd #fff0f2 0 1 0 0.5;
    	padding: 0.5em;
    	font-family:sans;
    	margin: 0;
    	rotate: 90;
    }

```
<?php
$pdf = PDF::Make();
				$pdf->loadView('bill.partials.forms.print', compact('bill', 'duplicate_invoice', 'diagnosis', 'layout'));
				$view = view('bill.partials.forms.print_revision', compact('bill', 'diagnosis'));

```

### This is a HTML code snippet I use

```
<div class="myfixed2">2 Praesent pharetra nulla in turpis. Sed ipsum nulla, sodales nec, vulputate in, scelerisque vitae, magna. Sed egestas justo nec ipsum. Nulla facilisi. Praesent sit amet pede quis metus aliquet vulputate. Donec luctus. Cras euismod tellus vel leo.</div>
```

**Comment by peyman-mohamadpour** [comment]
What do you mean by latest version? As it is subject of change in time. consider some other guy visiting this page in 2019. Please provide exact version.

That's possibly because of `overflow: auto;` CSS rule. other rules like `maring: 20px auto;` are the same and could cause this problem. Avoid non-numeric values in your CSS properties.

PDF generators all parse the HTML, CSS, so there is chance they do not comply with some CSS properties. You may see a list of CSS rules supported [here](https://mpdf.github.io/css-stylesheets/supported-css.html)

**Comment by finwe** [comment]
Please, provide a concrete mPDF and PHP version numbers and feel free to reopen after.

**Comment by prakashmalviya** [comment]
My PHP Version is: 7.1.4, mPDF version: 6.1, Laravel 5.2

**Comment by finwe** [comment]
Your code works fine with development branch, closed.
