### ISSUE TITLE
mpdf touches mb_internal_encoding when using core fonts only

### ISSUE THREAD

**Issue by qurben** [mpdf/mpdf#421]
### I have this problem/would like to have this functionality
When using mPDF with option `c`, core fonts only, the mb_internal_encoding is set to 'windows-1252'. Afterwards the encoding isn't reset to it's original value (UTF-8 in my case). Took me some trouble to figure out why `mb_substr` wasn't working anymore. This not only goes wrong with emoji, but everything outside 'windows-1252'

### These are mPDF and PHP versions I am using
Version 6.1.3

### This is a PHP code snippet I use

```
<?php
echo 'Before: ' . mb_substr('🐙', 0, 1);

$mpdf = new mPDF('c');
$mpdf->WriteHTML('');

echo 'After: ' . mb_substr('🐙', 0, 1);
```

### This is a HTML code snippet I use
N/A

**Comment by Klap-in** [comment]
The default encoding is set to `windows-1252`. 
An encoding is set by using `$mpdf->setMBencoding($encoding)`. (stored in (internal?) variable `$mpdf->mb_end`). This calls `mb_internal_encoding()` as well.

But note, in the constructor and `setFont()`, `setMBencoding` is called as well, based on certain settings. Changing this before WriteHTML is called, is only useful if you have to change your encoding in the processing of the pdf. 

I observe that this setter is not documented. I guess it is because it is maybe an internal property...

`mb_internal_encoding()` is also called in the `WriteHTML()`, setting the encoding as stored in `$mpdf->mb_end`

Workaround sofar: Using `mb_internal_encoding()` ensures that you have the encoding back you set your self.

You can find other info about setting the desired encoding during the processing of your pdf at
http://127.0.0.1:4000/fonts-languages/input-encoding.html 
(but that is not the restoring of changed settings , as you requested.)

**Comment by qurben** [comment]
I don't really mind that that while generating the pdf the internal encoding is set, but I would really like that the encoding is back to where it was after the pdf is generated. This way no unexpected things happen.

**Comment by finwe** [comment]
As the initial changes are done in the class constructor and without the user input mPDF is unable to know it won't be used, I haven't come up with anything better than the new `cleanup()` method which will restore the original mb_ values.
