### ISSUE TITLE
Mpdf v6.1.4 can not run on PHPv 7.1.7 (is this true?) but Mpdf v6.1.3 can

### ISSUE THREAD

**Issue by ucsdmath** [mpdf/mpdf#443]
Error I get:
mpdf/mpdf v6.1.4 requires php ^5.4.0 || 7.0.* -> your PHP version (7.1.7) does not satisfy that requirement.

A patch should not break right?  It maybe a typo in the composer.son file.
Keep the good work!  Thanks.

**Comment by finwe** [comment]
No, mPDF 6.x is not compatible with 7.1 because of very high count of type errors and other stuff.

**Comment by finwe** [comment]
Actually, I see I added the 7.1 constraint a half year ago, it just wasn't in a release.

Let me think about pros and cons of that, you are right that patch should not break but 6.x is broken on 7.1 anyway and I don't want to let it seem that it should work.

**Comment by ucsdmath** [comment]
OK, thanks.  I have been using v6.1.3 and PHP v7.1.7 and just tried to move to Mpdf v6.1.4 to get the patch (or latest version).  I just noticed the issue as not passing Travis CI for my stuff.  Anyway, thank you.

**Comment by finwe** [comment]
I have decided to keep the PHP constraint as is. The former constraint was defined before release of PHP 7.1 and it was an error that it was defined so loosely. And given that mPDF 6.x is broken on 7.1 anyway and there were no semver guarantees for mPDF<=6.*, it seems to me as a right thing to do. 

Since mPDF 7.0 mPDF should strictly conform to semver.

**Comment by ucsdmath** [comment]
OK, great! I will look forward to future releases.
