### ISSUE TITLE
Determine minimum PHP version for next major version, and lifecycle

### ISSUE THREAD

**Issue by marclaporte** [mpdf/mpdf#51]
@finwe wrote: "I believe mPDF officially supports PHP 5.2, however it can be run on PHP 4 when not using many advanced features. In the first round of code cleanup, I would like to retain this compatibility." Source: https://github.com/mpdf/mpdf/pull/35#issuecomment-112079764

@blueliquiddesigns wrote: "With this change it also would be good to decide on the minimum supported PHP version mPDF should support in the future. I'd recommend PHP5.3.2 which will allow us to take advantage of namespaces, autoloading, closures and SPL." Source:
https://github.com/mpdf/mpdf/pull/35#issuecomment-124966154

@danielhjames wrote: " I suggest there would be one branch for fixes to 6.0 which could potentially be the basis of an official 6.1 release, with Ian's approval, as these changes should be relatively easy to review. There would be another branch for a future mPDF 7.0 release which was refactored, with all the improvements we would like to see." Source: https://github.com/mpdf/mpdf/pull/47#issuecomment-148367129

PHP 5.4.x has reached end of life:
"Please note that according to the PHP version support timelines, PHP 5.4.45 is the last scheduled release of PHP 5.4 branch. There may be additional release if we discover important security issues that warrant it, otherwise this release will be the final one in the PHP 5.4 branch. If your PHP installation is based on PHP 5.4, it may be a good time to start making the plans for the upgrade to PHP 5.5 or PHP 5.6."
Source: http://php.net/archive/2015.php#id2015-09-04-4

The mPDF team should not spend additional time to support end-of-life versions of PHP. I propose that future major versions (ex.: mPDF 7) require a minimum of PHP 5.5, which offers significant performance gains:
https://thephp.cc/news/2013/06/php-5-5-out-of-the-box-bytecode-cache
And this will help with documented performance concerns:
http://mpdf1.com/manual/index.php?tid=266
http://mpdf1.com/manual/index.php?tid=408

Best regards,

M ;-)

**Comment by TomK** [comment]
A couple of comments on this in my PHP 7 pr: https://github.com/mpdf/mpdf/pull/35

**Comment by danielhjames** [comment]
I don't believe we can recommend or support any version of PHP which is no longer supported upstream. If someone really insists on using PHP4, end-of-lifed in 2008, their server is likely to be vulnerable to all kinds of exploits, but they still have the option to use Ian's mPDF 6.0 release.

I also don't see any point in supporting PHP 5.5 or earlier for the next generation mPDF 7.0 because Debian stable and the latest Ubuntu, for example, already ship PHP 5.6.x.  

So to summarise, we could have:

mPDF 6.x: minimum PHP 5.4, recommended PHP 5.6

mPDF 7.x minimum PHP 5.6, recommended PHP 7.0 or later

We might go even further, and do all mPDF 7.0 work for PHP 7.0 or later. mPDF 6.x from the GitHub repo will still be around for people who need to install mPDF on servers where the PHP version is fixed to 5.x. The kind of people interested in bleeding-edge mPDF development are not going to have a problem with upgrading their PHP to 7.0 or later.

Another benefit might be that we would not need to do any major PHP 7.0 (or later) changes in the mPDF 6.x branch. In other words, when PHP 5.x is eventually end-of-lifed, mPDF 6.x would also be end-of-lifed. That could potentially be on 28th August 2017, if there are no PHP 5 releases after 5.6, see: http://php.net/supported-versions.php 

That would save us having to backport lots of work from the mPDF 7.x branch. The mPDF 6.x branch would be strictly bugfixes only.

What do people think about that?

**Comment by finwe** [comment]
I'd keep 5.3 for 6.x branch, as after minor changes it will be bugfix only. For 7.x I'd go with 5.5 minimum.

With @TomK 's constructor PR and FPDF 1.6.0 update, mpdf should be functional on PHP 7.

I don't see too many benefits coming from sticking to PHP end-of-life dates.

**Comment by danielhjames** [comment]
I expect mPDF 6.x will work on some very old versions of PHP, but as a project it might be irresponsible for us to suggest that it is OK to run those versions if they expose web-facing servers to known vulnerabilities.

**Comment by finwe** [comment]
OK, I've thought this through and I agree with @danielhjames proposal of

> mPDF 6.x: minimum PHP 5.4, recommended PHP 5.6
> 
> mPDF 7.x minimum PHP 5.6, recommended PHP 7.0 or later

**Comment by marclaporte** [comment]
+1

**Comment by finwe** [comment]
Closing this.

**Comment by spytech** [comment]
I installed php version 7.0 on Server and Class mpdf stopped working and spent the display various errors . Please does anyone know how I can use the mpdf class in php 7.0?

**Comment by finwe** [comment]
@spytech Please, do not abuse closed issues with new error reports. File a new issue and provide necessary information: What is the version of mPDF you are using? Provide a code (PHP/HTML) sample that fails and also paste the errors displayed.

**Comment by sirobe** [comment]
Is there a way to set width of page but leave large auto or variable? Is for a product's ticket.
