### ISSUE TITLE
Getting Undefined index Undefined index: T for some exports

### ISSUE THREAD

**Issue by ber5ien** [mpdf/mpdf#532]
mpdf/mpdf/src/Mpdf.php
Using 7.0.1

![image](https://user-images.githubusercontent.com/854403/32490935-d0d4039e-c3ac-11e7-9552-4981ee139627.png)

**Comment by ber5ien** [comment]
The issue was happening specifically for the same views. The same views all the time. The only difference was the number of was (email subject) and customer address information.

To fix the issue i had got to revert to previous release.

Package operations: 0 installs, 2 updates, 0 removals
  - Updating mpdf/mpdf (v7.0.1 => v6.1.4): Loading from cache
  - Updating kartik-v/yii2-mpdf (dev-master 67980ab => v1.0.1):  Checking out 17fda1cb08

**Comment by finwe** [comment]
Please, post your PHP/HTML code snippet causing this. Without it, we are unable to review and/or fix this correctly.

**Comment by Devnco** [comment]
Hi I met the exact same issue. 

After some test it seems it depends of the number of character contained in a specific div of my HTML page.

It is hard to reproduce because it depends directly of the whole content of the file and how it will be proceed by MPDF.

In my case I'm generating a PDF with custom text content that can be injected by the user before the generation. 

I've notice that if I type 80 chars 'a' it broke MPDF with the same error than the previous one. If I type 79 it's ok, but it's not depend of the string length.

I've tried the same test with capitalize 'A', in that case 71 was ok and it broke at 72. 

I've also try to isolate the div that contain the text to only render this div with MPDF, in that case no issue at all. 

Could it be related to the processing done on the content to convert it ?

I'm also using mpdf/mpdf (v7.0.1)

I hope it helped.

**Comment by Klap-in** [comment]
Without example it is difficult to investigate and fix this. The mpdf code is not so simple... So please share the bigger, or small as possible, example of your test.

**Comment by kevinsmendes** [comment]
I am also, having the same issue: https://i.imgur.com/1oz06GE.png

**Comment by finwe** [comment]
Seriously, images are not helpful. post your PHP/HTML code snippet causing this. Without it, we are unable to review and/or fix this correctly.

**Comment by finwe** [comment]
Yes, I did. And yes, exactly as you say, I wanted you to post the PHP/HTML snippet you send to mPDF. I hope you didn't think I would re-type your code from error image where code portions are missing and the HTML is not present at all.

Now I finally have something to work with, thanks.

**Comment by cesarcgfg** [comment]
Same issue here. 
I had to revert to previous release.

**Comment by willypuzzle** [comment]
Same issue here

**Comment by cezar123** [comment]
same issue with a short simple html. attached below. hope it helps.
[mpdfBug.txt](https://github.com/mpdf/mpdf/files/1734797/mpdfBug.txt)
