### ISSUE TITLE
Remove class include/require calls and keep it on the autoloading

### ISSUE THREAD

**Issue by finwe** [mpdf/mpdf#62]
After FPDF update mPDF will require some sort of autoloading anyway. Let composer make the work for external libraries and mpdf itself.

**Comment by TomK** [comment]
I've been working on the FPDI update PR and theres some compatibility problem with autoloading.  Unless i'm barking up the wrong tree, I believe the issue is in https://github.com/Setasign/FPDI/blob/master/composer.json because classmap does not include `pdf_parser.php`.  Perhaps @JanSlabon would be able to add this if he has time?

**Comment by JanSlabon** [comment]
We need to leave this file from the classmap to be able to switch that file for our commercial parser add-on.

**Comment by TomK** [comment]
Ah sorry, i've had a closer look at the test and I think I can optimise pdf_parser out since fpdi_pdf_parser extends it.

**Comment by JanSlabon** [comment]
For completion: We check for the pdf_parser class through a simple class_exists() which may trigger the autoload from our add-on. If this is not installed via composer the file is simply required explicity.
