### ISSUE TITLE
font-family no effect when autoLangToFont is enabled

### ISSUE THREAD

**Issue by annProg** [mpdf/mpdf#670]
I use chinese and I add a custom font named `wqymicrohei`. In my css file ,set font-family for h1~h4
```
h1,h2,h3,h4 {
    font-family: wqymicrohei;
}
```

when `autoLangToFont` is false, all is ok, but if `autoLangToFont` is true, h1~h4 will display in `gb` font.

I want to use `wqymicrohei` to display h1~h4, but I also want to enable `autoLangToFont` because english char will display ugly using `gb` font.

When enable `autoLangToFont`, how to use different font for one language?

**Comment by finwe** [comment]
Please note that the Issue tracker serves mainly as a place to report bugs and request new features as noted in [Contributing guidelines](https://raw.githubusercontent.com/mpdf/mpdf/development/.github/CONTRIBUTING.md). Please do not abuse it as a general questions or troubleshooting location.

Use the the [mpdf tag](https://stackoverflow.com/questions/tagged/mpdf) at [Stack Overflow](https://stackoverflow.com/).

**Comment by jakejackson1** [comment]
I’ve also experienced this bug. I’ll write a full issue report when I’ve a moment and look into the root cause.

**Comment by finwe** [comment]
Feel free to reopen when you have enough evidence it really is a bug. Thanks!

**Comment by jakejackson1** [comment]
### I found this bug / would like to have this new functionality
When `'autoLangToFont' => true` AND `'autoScriptToLang' => true` are used in conjunction with each other, the font found in `LanguageToFont` overrides the font set with `font-family`, even though the `font-family` font supports the current character set. 

This problem doesn't appear to effect English and it'll happily use the current `font-family` font if the character set supports it. I suspect any of the European languages found in `LanguageToFont` which gets set to `$coreSuitable = true;` have no issue. 

Because I couldn't replicate the problem with `'autoLangToFont' => true` or `'autoScriptToLang' => true` alone I'm flagging this as a bug. 

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
Latest development branch ed27fb22774fbd67b41074beabe169ff8ad61c24, using PHP7.2.

### This is a PHP code snippet I use

Here's the font used (it's quite pronounced to make it easy to see the problem at hand): [BLK-BangLi-Ko-Sa-Na.zip](https://github.com/mpdf/mpdf/files/1779423/BLK-BangLi-Ko-Sa-Na.zip)

```
<?php
$defaultConfig = (new Mpdf\Config\ConfigVariables())->getDefaults();
$fontDirs = $defaultConfig['fontDir'];

$defaultFontConfig = (new Mpdf\Config\FontVariables())->getDefaults();
$fontData = $defaultFontConfig['fontdata'];

$mpdf = new \Mpdf\Mpdf([
	'autoLangToFont' => true,
	'autoScriptToLang' => true,

	'fontDir' => array_merge($fontDirs, [
		__DIR__ . '/font',
	]),

	'fontdata' => $fontData + [
			'blkbangli' => [
				'R' => 'BLK-BangLi-Ko-Sa-Na.ttf',
			]
		],
]);

$mpdf->WriteHTML('
<style>
	body {
		font-family: BLKBangli;
		font-size: 200%;
	}
</style>

This is some English. <br>

จ,ช,ซ,ฌ,ฎ,ฏ,ฐ,ฑ
');

$mpdf->Output();
```

**Comment by annProg** [comment]
## php code
```
<?php

require_once __DIR__ . '/vendor/autoload.php';

$defaultConfig = (new Mpdf\Config\ConfigVariables())->getDefaults();
$fontDirs = $defaultConfig['fontDir'];
$defaultFontConfig = (new Mpdf\Config\FontVariables())->getDefaults();
$fontData = $defaultFontConfig['fontdata'];

$mpdf = new \Mpdf\Mpdf([
	'mode' => '+aCJK',
	'fontdata' => $fontData + [
		'wqymicrohei' => [
			'R' => 'wqy-microhei.ttc',
			'B' => 'wqy-microhei.ttc',
			'TTCfontID' => [
				'R' => 1,
				'B' => 1
			]	
		]
	],
	'default_font' => 'dejavuserifcondensed',
]);
$mpdf->autoScriptToLang = true;
$mpdf->baseScript = 1;
$mpdf->autoVietnamese = true;
$mpdf->autoArabic = true;
$mpdf->autoLangToFont = true;

$mpdf->WriteHTML('<html><head></head><body style="font-family:sans-serif;"><h1 style="font-family:wqymicrohei;">Title with Chinese 中文 文泉驿雅黑</h1>body with english and Chinese. <br>正文包含中文和英文</body></html>');
$mpdf->Output('hello.pdf');
```
## pdf output
![image](https://user-images.githubusercontent.com/4145852/36967189-06583b4e-209a-11e8-8855-aec2b6f413d3.png)

## pdf output when disable autoLangToFont 
both English and Chinese char in title will display in `wqymicrohei` as expected, and English in body will 
automatically set to `dejavuserifcondensed`, but Chinese in body can't display
![image](https://user-images.githubusercontent.com/4145852/36967274-390d448a-209a-11e8-97df-2faf053c9180.png)

## pdf output when set body font-family with gb
In order to display Chinese in body, modify body style to (add gb):
```
<body style="font-family:sans-serif, gb;">
```
Then title will be display as expected , but all char in body will use gb font, include English char. but English char in gb font will display ugly
![image](https://user-images.githubusercontent.com/4145852/36967669-4f57a69e-209b-11e8-994d-2f7262a0281d.png)

**Comment by jakejackson1** [comment]
@annProg I reviewed this in detail. From what you've told me, the main language in the PDF will be Chinese. Since that's the case, you need to set the `baseScript` to your language. I believe it's `$mpdf->baseScript = \Mpdf\Ucdn::SCRIPT_HAN;`, [but there are quite a few scripts to choose from](https://github.com/mpdf/mpdf/blob/development/src/Ucdn.php#L12-L114). This will prevent `autoScriptToLang` from marking up the Chinese characters and automatically converting the font. 

In your HTML, set the `font-family` to `wqymicrohei` (or what ever default font you want to use). The English characters will be converted to the default fallback font. 

@finwe after reviewing the functionality of `autoScriptToLang` and `autoLangToFont` in depth, as well as how `baseScript` functions, I believe you can close this issue. It's not a bug, users just need to be correctly setting `baseScript` to their default script/language if they plan to use these configuration options together.

**Comment by annProg** [comment]
@jakejackson1 Thanks a lot. After fix my code and now it works fine
```
$mpdf->autoScriptToLang = true;
$mpdf->baseScript = \Mpdf\Ucdn::SCRIPT_HAN;
$mpdf->autoVietnamese = true;
$mpdf->autoArabic = true;
$mpdf->autoLangToFont = true;

$mpdf->WriteHTML('<html><head></head><body style="font-family:sans-serif,gb;"><h1 style="font-family:wqymicrohei;">Title with Chinese 中文 文泉驿雅黑</h1>body with english and Chinese. <br>正文包含中文和英文</body></html>');
$mpdf->Output('hello.pdf');
```


```
[root@localhost mpdf]# pdffonts hello.pdf 2>/dev/null
name                                 type              emb sub uni object ID
------------------------------------ ----------------- --- --- --- ---------
STSongStd-Light-Acro-UniGB-UTF16-H   CID Type 0        no  no  no       6  0
STSongStd-Light-Acro,Bold-UniGB-UTF16-H CID Type 0        no  no  no       9  0
STSongStd-Light-Acro,Italic-UniGB-UTF16-H CID Type 0        no  no  no      12  0
STSongStd-Light-Acro,BoldItalic-UniGB-UTF16-H CID Type 0        no  no  no      15  0
MPDFAA+WenQuanYiMicroHei             TrueType          yes yes yes     18  0
MPDFAA+DejaVuSansCondensed-Bold      CID TrueType      yes yes yes     23  0
MPDFAA+DejaVuSansCondensed           CID TrueType      yes yes yes     30  0
```

**Comment by finwe** [comment]
@jakejackson1 Can the documentation be updated to better address this?

**Comment by annProg** [comment]
@jakejackson1 After set `baseScript` to `SCRIPT_HAN`, Latin characters will ignore font-family:
```
<p style="font-family:wqymicrohei;">body with english and Chinese.<br>正文包含中文和英文</p>
```

and Latin characters  will auto set to `dejavuserifcondensed`.  Seems to be no solution.

**Comment by jakejackson1** [comment]
@finwe no problem. I'll look at enhancing the documentation in this regard.

@annProg if you want control of the English font, you need to configure what fallback font is used by `autoLangToFont`. [See example 4 in the documentation on fonts](https://mpdf.github.io/fonts-languages/fonts-in-mpdf-7-x.html).

**Comment by annProg** [comment]
@jakejackson1 Thanks a lot, I will try.

**Comment by finwe** [comment]
Closing as resolved.
