### ISSUE TITLE
Tags with 0 as value not displaying.

### ISSUE THREAD

**Issue by finwe** [mpdf/mpdf#82]
Repost from mPDF forum user TAlmasy:

When a tag  is made with a 0 value inside it will not render.
This does NOT happen in 5.7, only in 6.0

```
<?php
$prob = 'hi<b>0</b><b>1</b>';

include_once($_SERVER['DOCUMENT_ROOT']."/mpdf60/mpdf.php");
$mpdf=new mPDF();
$mpdf->WriteHTML($prob);
$mpdf->Output();
?>
```

This can be fixed by modifying line 21646 and adding the `&& $arrayaux[$i][0]!=='0'` bit.

```
    // Remove empty items // mPDF 6
    for($i=$array_size-1; $i > 0; $i--) {
        if (empty($arrayaux[$i][0]) && $arrayaux[$i][0]!=='0' && $arrayaux[$i][16]!=='0' && empty($arrayaux[$i][7])) {
            unset($arrayaux[$i]);
        }
    }
```

**Comment by mburnicki** [comment]
I'd like to submit a pull request to fix this, and I'd like to do this for the stable branch, so this will be fixed in 6.1. Is this OK, and will the fix be merged upstream to the development branch?
I'm new to github and not too familiar with its "best practices".

**Comment by finwe** [comment]
The 6.x branch is frozen for non-critical fixes. This is not a cricital fix, so please base your PR on the development branch and the fix will be available in 7.x releases.

**Comment by mburnicki** [comment]
I just had a closer look at the relevant code in different mpdf versions.

The problem was observed with 6.0, which is still used by the dokuwiki project.
The line labelled 'fix' is the proposed fix from a posting in the old mpdf forum, which worked for me.
In 6.1 and -dev the code has been changed, and though it doesn't match the original proposal for a fix, it seems to work properly:

```
6.0: if (empty($arrayaux[$i][0]) && $arrayaux[$i][16]!=='0' && empty($arrayaux[$i][7])) {
fix: if (empty($arrayaux[$i][0]) && $arrayaux[$i][0]!=='0' && $arrayaux[$i][16]!=='0' && empty($arrayaux[$i][7])) {
6.1: if (empty($arrayaux[$i][0]) && (isset($arrayaux[$i][16]) && $arrayaux[$i][16] !== '0') && empty($arrayaux[$i][7])) {
dev: if (empty($arrayaux[$i][0]) && (isset($arrayaux[$i][16]) && $arrayaux[$i][16] !== '0') && empty($arrayaux[$i][7])) {
```
I've just downloaded the mpdf 6.1 zip file from git here, replaced the original mpdf code in my dokuwiki installation by the 6.1 version, and the problem I had observed with 6.0 doesn't occur anymore.

So I think this bug can simply be closed.
Thanks.

**Comment by finwe** [comment]
Cool. Thanks for your insight!
