### ISSUE TITLE
How to remove block elements margins?

### ISSUE THREAD

**Issue by stratboy** [mpdf/mpdf#836]
Hi, I noticed that block elements (ex. div) have some kind of margins by default, and it seems I cannot reset them via css. So how to?

**Comment by finwe** [comment]
Please note that the Issue tracker serves mainly as a place to report bugs and request new features as noted in [Contributing guidelines](https://raw.githubusercontent.com/mpdf/mpdf/development/.github/CONTRIBUTING.md). Please do not abuse it as a general questions or troubleshooting location.

Use the the [mpdf tag](https://stackoverflow.com/questions/tagged/mpdf) at [Stack Overflow](https://stackoverflow.com/).

**Comment by stratboy** [comment]
>>>> Use the the mpdf tag at Stack Overflow.

I did, but:

- didn't receive your answer
- got downvoted 2 times

So maybe you could consider answering.

**Comment by finwe** [comment]
I certainly would consider answering, but I don't know the answer and currently have no time to investigate this.

I direct general questions and troubleshooting to Stack Overflow because there is much bigger chance to get it to someone who can answer than here. But that surely doesn't mean that you get an answer right away or at all.

Sure, in asking questions at SO you have to abide by their rules. Given your SO reputation I'd guess you have some experience in how SO works. No wonder you get downvoted when the question is just two lines of text, with no code examples, MCVE, etc.

**Comment by stratboy** [comment]
Since you're obviously a Super Pro, you sure know that SO rules do not let us to ask for 3rd party libraries. So when asking to go there instead of answering here, you should then protect people and answer there.
