### ISSUE TITLE
File annotations not working after upgrading to PHP 7.2

### ISSUE THREAD

**Issue by Zolcsi67** [mpdf/mpdf#848]
### I found this bug / would like to have this new functionality

Annotations with file attachments are not working with PHP 7.2 (tested on PHP 7.2.9 and 7.2.7). It was fine before, but stopped working after upgrading. The annotation is show fine, but there is no file attachment

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
PHP 7.2.9/OSX and 7.2.7/Ubuntu tested using CLI mode. mPDF is installed via composer and the version is 7.1.4

### This is a PHP code snippet I use

```
<?php

require_once 'vendor/autoload.php';
$mpdf = new \Mpdf\Mpdf();

$mpdf->WriteHTML('Hello World');
$mpdf->Annotation("File annotation", 0, 0, 'Note', '', '', 0, false, '', 'annot.xml');
$mpdf->WriteHTML('Hello World');

$mpdf->Output('filename.pdf');

```

**Comment by Klap-in** [comment]
Does it make a difference which file you attach? If so, please provide an example file.

**Comment by Zolcsi67** [comment]
@Klap-in No, it doesn't. I just tried to attach a PDF file and it produces the same result

**Comment by finwe** [comment]
Since mPDF v7.0.0, embedded annotation files must be explicitly allowed by setting `allowAnnotationFiles` configuration key to true. Otherwise, the file attribute of annotation tag will be ignored.

Code below works with mPDF 7.1.5 and both PHP 7.1 and 7.2:

```
$mpdf = new \Mpdf\Mpdf(['allowAnnotationFiles' => true]);

$mpdf->Annotation("File annotation", 0, 0, 'Note', '', '', 0, false, '', 'assets/tiger.jpg');
```

I don't see how your code example could work with PHP 7.1 either, unless you were using mPDF 6.x before.

Will note the allowAnnotationFiles config key in the documentation, it is now present only in the [example file of annotations](https://github.com/mpdf/mpdf-examples/blob/development/example36_annotations_and_attached_files.php).

I have also prepared a quickfix for notice about undefined index while running your code example which will be commited to development branch soon.

Anyway, thanks for the catch.

**Comment by Zolcsi67** [comment]
@finwe Thanks for the help! (Yep, I was migrating from mPDF6)
