### ISSUE TITLE
Wrong PHP requirements, myclabs/DeepCopy dependencie break composer now

### ISSUE THREAD

**Issue by ETNyx88** [mpdf/mpdf#964]
Hello,

recently myclabs/DeepCopy update their php requirements to "php": "^7.1"  (https://github.com/myclabs/DeepCopy/commit/9f807201f6e6a8b7ab3582d815511d1807c9c202#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780) as part of upgrade to 1.8.1 (https://github.com/myclabs/DeepCopy/blob/1.8.1/composer.json) this change resolve in failing of Composer. So current requirement by mpdf doesn't seems to be valid anymore (5.6 || 7.0)  

```
$php composer.phar install --no-plugins --no-scripts
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for myclabs/deep-copy 1.8.1 -> satisfiable by myclabs/deep-copy[1.8.1].
    - myclabs/deep-copy 1.8.1 requires php ^7.1 -> your PHP version (7.0.27) does not satisfy that requirement.
  Problem 2
    - myclabs/deep-copy 1.8.1 requires php ^7.1 -> your PHP version (7.0.27) does not satisfy that requirement.
    - mpdf/mpdf v7.1.7 requires myclabs/deep-copy ^1.7 -> satisfiable by myclabs/deep-copy[1.8.1].
    - Installation request for mpdf/mpdf v7.1.7 -> satisfiable by mpdf/mpdf[v7.1.7].

ERROR: Job failed: exit code 1
```
This is Job report from CI runing composer on Debian/stable (Stretch) on PHP 7.0

**Comment by finwe** [comment]
This most likely is not an issue of mPDF.

It seems you have previously installed dependencies with a newer version of PHP and then commited composer.lock with myclabs/deepcopy version locked at 1.8.1 which will not work with older PHP.

Either do not commit your composer.lock file, or specify PHP 7.0 version in config/platform/php key of your composer.json

With clean composer installation (composer update, or composer install without composer.lock file), composer installs the last myclabs/deepcopy version compatible with older versions of PHP.

CI of mPDF itself works correctly even with PHP 5.6: https://travis-ci.org/mpdf/mpdf/jobs/479344164

Please verify this hypothesis and if you still think the issue is with mPDF, feel free to reopen the issue with more information.
