### ISSUE TITLE
Adopt PSR-2: Coding Style

### ISSUE THREAD

**Issue by machour** [mpdf/mpdf#986]
I would love to see mPDF using [PSR-2](https://www.php-fig.org/psr/psr-2/) code style.

As that PSR says, it "reduce cognitive friction when scanning code from different authors".
Reviewing #841, I totally feel the need for that.

If it's okay, I would like to provide the PR for this change, once v8 is released.

**Comment by finwe** [comment]
mPDF already adopts PSR2 with the only exception of tabs instead of spaces (and actually some other excluded rules from codesniffer PSR2 rules reflecting the state of the codebase, see https://github.com/mpdf/mpdf/blob/development/ruleset.xml).

I do not want to change this state. For more finegrained spacing rules (such as spaces around different tokens), PSR2 will not help as it does not enforce any particular approach to this.

**Comment by finwe** [comment]
fun fact: the codebase contains 264,568 tab characters. When converted to spaces, the project file size grows considerably.

**Comment by machour** [comment]
hahahaha, good one :D 

I really don't have a problem with tabs, it was the weird formatting I saw in that PR that puzzled me (example: `if ( ! isset($this->register[$name])) {`)

**Comment by finwe** [comment]
yes, that's exactly what PSR-2 AFAIK does not address (or it will be reported as a violation by codesniffer in CI)
